ALTER TABLE projects ADD COLUMN IF NOT EXISTS html_content TEXT DEFAULT '';
ALTER TABLE projects ADD COLUMN IF NOT EXISTS css_content TEXT DEFAULT '';
ALTER TABLE projects ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
